### ISSUE TITLE
error: ‘else’ without a previous ‘if’

### ISSUE THREAD

**Issue by mufeng-74** [TriangleLDP/TriangleLDP#1]
Hello, when I am installing the C/C++ code, when I run to the make step, the following error appears, what should I do to solve it? Thanks a lot!

`g++ -march=native -O3 -std=c++11 -isystem ./include -MMD   -c -o TriangleCounting.o TriangleCounting.cpp
TriangleCounting.cpp: In function ‘int main(int, char**)’:
TriangleCounting.cpp:2198:3: error: ‘else’ without a previous ‘if’
 2198 |   else if (Alg == 1){
      |   ^~~~
TriangleCounting.cpp: In function ‘void ReadEdges(std::map<int, int>*, int*)’:
TriangleCounting.cpp:93:24: warning: ignoring return value of ‘char* fgets(char*, int, FILE*)’, declared with attribute warn_unused_result [-Wunused-result]
   93 |  for(i=0;i<3;i++) fgets(s, 1024, fp);
      |                   ~~~~~^~~~~~~~~~~~~
TriangleCounting.cpp: In function ‘int main(int, char**)’:
TriangleCounting.cpp:2007:24: warning: ignoring return value of ‘char* fgets(char*, int, FILE*)’, declared with attribute warn_unused_result [-Wunused-result]
 2007 |  for(i=0;i<2;i++) fgets(s, 1024, fp);
      |                   ~~~~~^~~~~~~~~~~~~
TriangleCounting.cpp:2027:10: warning: ignoring return value of ‘char* fgets(char*, int, FILE*)’, declared with attribute warn_unused_result [-Wunused-result]
 2027 |     fgets(s, 1024, fp);
`

**Comment by tmrkm** [comment]
It is strange. Line 2198 of TriangleCounting.cpp states: "if (Alg == 1){". There is no "else if (Alg == 1)" in TriangleCounting.cpp. Could you check it?
