### ISSUE TITLE
Is there any formula giving the expected loss on a specific graph data?

### ISSUE THREAD

**Issue by dongxudongxu** [TriangleLDP/TriangleLDP#2]
It takes such a long to complete the whole protocol on big graph data. 
I wander if there is a formula can approximately predict the l2 loss or relative error on a specific graph?
Thanks a lot!

**Comment by tmrkm** [comment]
We analyzed the utility of our protocols in our paper (Theorems 2 and 4 and Table 1): https://arxiv.org/abs/2110.06485
